services:
  app:
    build: .
    container_name: freq_counter
    restart: always
    env_file:
      - .env
    expose:
      - "${FLASK_PORT}"
    depends_on:
      - metrics_db
    volumes:
      - .:/app
    command: >
      sh -c "flask db upgrade && gunicorn -w 4 -b 0.0.0.0:${FLASK_PORT} run:app"

  metrics_db:
    image: postgres:16-alpine
    container_name: metrics_db
    restart: always
    env_file:
      - .env
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - metrics_db

  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.template.conf:/etc/nginx/templates/default.conf.template:ro
    env_file:
      - .env
    depends_on:
      - app

volumes:
  postgres_data:
  pgadmin_data: