services:
  app:
    build: .
    container_name: freq_counter
    restart: always
    env_file:
      - .env
    expose:
      - "${FLASK_PORT}"
    depends_on:
      - metrics_db
    volumes:
      - .:/app
      - ./app/media:/app/app/media
    command: >
      sh -c "flask db upgrade && gunicorn -w 4 -b 0.0.0.0:${FLASK_PORT} run:app"

  metrics_db:
    image: postgres:16-alpine
    container_name: metrics_db
    restart: always
    env_file:
      - .env
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/logs:/var/log/nginx
    env_file:
      - .env
    depends_on:
      - app

volumes:
  postgres_data:
