services:
  app:
    build: .
    container_name: freq_counter
    env_file:
      - .env
    ports:
      - "${FLASK_PORT}:5000"
    depends_on:
      - metrics_db
    volumes:
      - .:/app
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"

  metrics_db:
    image: postgres:16-alpine
    container_name: metrics_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: